### ISSUE TITLE
Library built for .Net Standard 

### ISSUE THREAD

**Issue by SteGriff** [NordicID/nur_sdk#1]
Hi NordicID team,

I am currently integrating an EXA51 for a Windows application via bluetooth. Thank you for the UWP demo app and the accompanying UWP library, these are useful.

However, it seems that the UWP lib is the only version for Windows which supports bluetooth. Our application is server-based and UWP is not a very good fit. I would like to write a .Net Core console app instead.

Would it be possible for you to export your functionality as in `NurApiDotNetUWP.dll` v1.9.6 as a **.Net Standard** type library instead? In this case, it could be used not only with UWP but also with .Net Core.

I realise this may be difficult or impossible for technical reasons (access to the Windows bluetooth APIs possibly?). If you have any other way to integrate with bluetooth on Windows outside of the UWP constraints I would be interested to hear it :)

Thanks,
Ste

**Comment by mikkonid** [comment]
Hi Ste,
As far as I know windows 10 BLE api is only available for UWP apps. 
However, there's way to use UWP api in WinForms app, but it's kind a hackish. 

What platform you're running your dotnet core app?

**Comment by SteGriff** [comment]
Hi Mikko,

Thanks for the reply. I see, that restriction makes sense. I am currently looking at having a minimal UWP app which fires the data from the EXA51 into a local queue service where it can be picked up by another service. This microservice structure gives us some flexibility for future extension as well.

My platform is a just a common 64 bit desktop PC.

Thanks again!
Ste

**Comment by SteGriff** [comment]
I am happy to close this
