### ISSUE TITLE
Issue with Serial Number format

### ISSUE THREAD

**Issue by VincentTruevolve** [NordicID/nur_sdk#10]
Good day,

I am having some trouble retrieving the serial number of a Nordic ID Stix device in a windows environment. Specifically, when calling NurApiGetReaderInfo, I see that the struct NUR_READERINFO is in fact not being populated at all.
It seems that the C API does provide the serial number correctly when I query it on a Linux x86_64 machine, but when I run the exact same code sample which is written in C++11 on a Windows machine, the serial number variable is empty. 

To provide some context in which this problem occurs, I will describe our environment:
We provide a wrapper for different RFID readers that looks the same regardless of what physical reader is actually used.
These wrappers are written in C++11 (making sure not to use any platform/architecture specific headers/APIs) and we use 
Swig to provide easy-to-use interfaces in Java, Golang and C#. We use all of these wrappers in all of the mentioned languages on Windows and Linux (x86_64 and arm) in multiple different applications and services.
One of our clients depends on the serial number to identify work stations. Therefore it is important for us to be able to read the serial number of the Stix device via the C API.
In Linux, we are using GCC/G++ to compile, and for Windows, we also use GCC/G++ via MinGW. For both these cases, we use an Ubuntu-based docker image to compile/cross-compile.
The docker image we use to build with is publicly available here: https://hub.docker.com/r/truevolve/gcc-cmake-mingw/

The error message returned in windows reads as follows:
    I n v a l i d  c o m m a n d  p a r a m e t e r ( s ) ;  I n v a l i d   f u n c t i o n  p a r a m e t e r ( s )
Additionally, it was discovered that the sizeof(struct NUR_READERINFO) returns 192 in the Windows environment.

Please note that the reading and writing of tags is still entirely possible using the same hApi handle.  

I have attempted to change the compiler setting for char set in Windows, to no avail, using the following options:
UTF-8,
UTF-16,
UTF-32, &
ISO 8859-1.

Kind Regards, 
Vincent Mattana

**Comment by mikkonid** [comment]
Hi Vincent,

We've not tried NurApi winth mingw gcc, but it should be possible to use it.

All our win32 libraries are compiled unicode enabled.
How have you set compiler options for UTF-16 ?

You need to have at least defined _UNICODE, UNICODE and _WIN32 in your compiler settings.
And maybe -municode might be needed also.

Best regards,
Mikko Lähteenmäki

**Comment by VincentTruevolve** [comment]
Hi Mikko, 
I have tried the suggestions you have made, and while it does solve the issue of the error appearing, unfortunately, it still does not resolve the issue of the serial number not being propagated through to windows properly. 
I have made a sample repo on bitbucket to illustrate the issue so that hopefully you can reproduce it on your side. Please have a look at https://bitbucket.org/truevolve/nordicwrapserialsample/src/master/

The executable can be found under 'Downloads'. 

Please note that using the flag '-municode' broke the building procedure, and as such, it was not included. However, UTF-16,  _UNICODE, UNICODE and _WIN32 were included and seems to have resolved the NUR_API error, but is still not giving expected behaviour.

Regards, 
Vincent Mattana

**Comment by mikkonid** [comment]
Hi Vincent,

Thanks for the sample code, I spotted the problem. 
As NurApi strings are UTF-16, you'll need to convert them properly to std::string.

Here's one way doing it:
```
diff --git a/ConnectionWrapper.cpp b/ConnectionWrapper.cpp
index 4f05bad..f9f2078 100644
--- a/ConnectionWrapper.cpp
+++ b/ConnectionWrapper.cpp
@@ -75,9 +75,11 @@ ResponseObject ConnectionWrapper::getSerial() {
         loge("NurApi error: " << ss.str());
         myResponse.setError(ss.str());
     } else {
-        stringstream ss;
-        ss << readerInfo->serial ;
-        myResponse.setResponse(ss.str());
+        // Create std wide string from UTF-16 string
+        std::wstring wSerialStr(readerInfo->serial);
+        // Convert std::wstring to std::string
+        std::string serialStr( wSerialStr.begin(), wSerialStr.end() );
+        myResponse.setResponse(serialStr);
         myResponse.setError("OK");
     }
```

Let me know if this works for you.

**Comment by VincentTruevolve** [comment]
Good day Mikko, 
Unfortunately, that solution did not work for me as the issue persists, that I am not able to get the serial in the correct format on Windows. 
A number of attempts were made using a variety of techniques, including the suggestion that you have made, to no avail.

Please advise, and feel free to refer to the sample repo: https://bitbucket.org/truevolve/nordicwrapserialsample/src/master/

Regards, 
Vincent Mattana

**Comment by mikkonid** [comment]
That's strange, it works with me.
Here's output:
```
$ ./readSerial.exe
DEBUG: ConnectionWrapper.cpp @ 29 Opening the connection
Read the following serial from device: [K134700461]
Read the following error: [OK]

DEBUG: ConnectionWrapper.cpp @ 91 Closing the connection
```

However, I did not see exact same code in your repo.

Please try following complete ConnectionWrapper.cpp with all strings converted and helper funcs.
https://gist.github.com/mikkonid/dc8afdc74ece44af7970e9e4135cddd3


BR,
Mikko

**Comment by VincentTruevolve** [comment]
Thank you for all the assistance, Mikko! 
It is working now. 

BR 
Vincent Mattana
