### ISSUE TITLE
[Feature Request] Add Barcode Type to AccBarcodeResult

### ISSUE THREAD

**Issue by brandscill** [NordicID/nur_sdk#22]
It would be useful to know the Barcode Type you scanned (Code-128, EAN, Code39 for example).

Most other industrial scanners can provide this data but I can't find anywhere in the current Api where this data is offered.

**Comment by mikkonid** [comment]
It is actually possible, but agreed, not so obvious.

You can find documentation for imager used in our handheld device in section 1.12.5 2d Imager:
https://www.nordicid.com/wp-content/uploads/Nordic_ID_EXA51e_User_Guide_2v4.pdf

Here's API config string example to enable standard ISO15424 3digit identifier and '-' character prefix:
```@MENU_OPTO@ZZ@RY@$1@5N@ZZ@OTPO_UNEM@```

Here's opticonfigure link for using scanner to enable config:
http://opticonfigure.opticon.com/sl/?z=jO--100.2--100.6G--100&a=4&b=2&d=1

Here's one list of standard AIM identifiers:
https://support.honeywellaidc.com/s/article/List-of-barcode-symbology-AIM-Identifiers

Hope this helps.

BR,
Mikko

**Comment by brandscill** [comment]
Thanks Mikko, all sorted now.

Be good to get this info on the GitHub page.
