### ISSUE TITLE
Multiple tag inventory with same EPC

### ISSUE THREAD

**Issue by gal1990** [NordicID/nur_sdk#23]
Dear Nordic developer team,

We are working on "Order prepare" android application, for hardware we are using NORDIC ID HH85 Gun Reader. 
We integrated your "NurApi.jar" library into our android app but unfortunately we can't make inventory for multiple tags which have same EPC because how I see in "NurTagStorage"  they are stored (HashMap) by EPC.

Question:
- Is there any solution to store the TAGs by TID?

**Comment by AriPoy** [comment]
Solution in this case is to read tags using "InventroyRead" command. There is possible to select bank and count of words to read. [Sample of InventoryRead](https://github.com/NordicID/nur_sample_java/blob/289a3efdba41e0f27078853eff27eba7ad4270d4/samples/04_InventoryRead/src/com/nordicid/testapplication/Example.java#L58)
Change irType to IRTYPE_DATAONLY to receive only TID and make sure length and bank settings are correct.

**Comment by gal1990** [comment]
> Solution in this case is to read tags using "InventroyRead" command. There is possible to select bank and count of words to read. [Sample of InventoryRead](https://github.com/NordicID/nur_sample_java/blob/289a3efdba41e0f27078853eff27eba7ad4270d4/samples/04_InventoryRead/src/com/nordicid/testapplication/Example.java#L58)
> Change irType to IRTYPE_DATAONLY to receive only TID and make sure length and bank settings are correct.

**Comment by gal1990** [comment]
@AriPoy  Thank you for fast answer!
If I set to I receive only TID am I able to read also the EPC? I need both information.

**Comment by AriPoy** [comment]
Use NurApi.IRTYPE_EPCDATA to receive both

**Comment by gal1990** [comment]
@AriPoy , yes if I using NurApi.IRTYPE_EPCDATA I receive both information but the problem is that the NurApi.mStorage hashmap stores the tags by EPC key and not by TID. And if I have multiple tag with same EPC I don't know how many tags were read. I need the same mechanism as with NurApi.IRTYPE_EPCDATA but stored by TID. Could you help me in this?
