### ISSUE TITLE
Request Native driver to support Mac OS

### ISSUE THREAD

**Issue by Jackym** [NordicID/nur_sdk#3]
The current native library only support Linux and Windows platforms. Wondering if it is possible to support Mac OS platform as well. As checking the header file NurOS.h, there is already Marco definition for Mac OS, so should be straight forward to compile the library for Mac. 

If this could come true, it would be pretty helpful to the development. Thanks in advance!

**Comment by nullfx** [comment]
use the [NurAPIBluetooth.framework from the iOS sample](https://github.com/NordicID/nur_sample_ios) add [NurOs_macOS.h](https://github.com/NordicID/nur_sdk/blob/master/native/include/NurOs_macOS.h) from the the includes here, edit NurAPIBluetooth.h switch UIKit for AppKit.

disclaimer: haven't actually used it but that at least compiles on my mac.  should work in theory.

**Comment by Jackym** [comment]
@nullfx Thanks for your advise. However the repo you mentioned are using objective-c and swift, so it is not straightforward for me mitigate them into my project. I'm using C/C++ crossing Mac and Linux, and the native library for Linux works for me perfectly, so I just need the same library compiled in Mac OS, then everything should work out together.

**Comment by jan-ekholm** [comment]
A macOS sample app is in the works, but the first version of that demo targets the Sampo type Ethernet connected readers. For that a minimal wrapper on top of the normal NurAPI SDK was created without any extra functionality like the iOS Bluetooth version has.

You are looking at using BLE readers with macOS? There should not be anything that is specifically iOS only about the current NurAPIBluetooth framework, so it should be fairly easy to make a macOS version if required.

**Comment by Jackym** [comment]
I tried to communicate with the UHF readers, including AR55 and AR85 through Ethernet, so the Bluetooth framework doesn't seem work for me. But I figured out to use the Embedded NUR protocol to connect to the readers :)

Thanks you guys' advices!
