### ISSUE TITLE
NurApiConnectSerialPort; NUR API error 4097: Transport error - raspberrypi

### ISSUE THREAD

**Issue by Darkus6767** [NordicID/nur_sdk#4]
Hello. I'm making application in C#. I'm trying to connect to reader (enur_ax) by raspberry pi via USB, but I have some problems. When I try to connect by PC there is not any problem, but on raspberrypi (linux), I've got error mentioned in the title of this issue. I checked that reader is connected to raspberry in dev.
I used this method to connect to my reader

_hNur.ConnectSerialPort("/dev/ttyACM0",0),
SetUsbAutoConnect method unfortunately doesn't work (is not supported, information from putty console).

What's a solution? Maybe I should configure my USB Ports in raspberry pi in some way?

Thank you in advance :)

**Comment by Darkus6767** [comment]
Solution: There is a mistake in documentation to ConnectSerialPort method. Second parameter is about baudrate, there is a tip which says that I should write one of this options: 0,1,2,3,4,5. That's an error, you have to write for example NurApi.DEFAULT_BAUDRATE :) 
So code should looks like this:
`
 _hNur = new NurApi();
_hNur.ConnectSerialPort("/dev/ttyACM0", NurApi.DEFAULT_BAUDRATE);
`
Reader is connected to raspberrypi via USB port.

**Comment by mikkonid** [comment]
Yeah, documentation is indeed wrong. 
Thanks for the tip, docs will be fixed in next release.
