### ISSUE TITLE
TAM Issue on Linux

### ISSUE THREAD

**Issue by VincentTruevolve** [NordicID/nur_sdk#7]
Good day,
I am having some difficulty implementing the following two calls:

**NurApiISO29167_10_TAMByEPC**
```
NurApiISO29167_10_TAMByEPC(HANDLE hApi, BYTE *epcBuffer, DWORD epcBufferLen, struct NUR_TAM_PARAM *tamParam, struct NUR_TAM_RESP *pTAMResp)
```
Using the following parameter set for example:
```
    NUR_TAM_PARAM tamParam{};
    tamParam.tam2 = TRUE;
    tamParam.decrypt = TRUE;
    tamParam.keyNum =1;
    tamParam.mpi= static_cast<DWORD>(memory);
    tamParam.protMode=0;
    tamParam.offset= static_cast<DWORD>(blockOffset);
    tamParam.blockCount= static_cast<DWORD>(blockCount);
    for (unsigned int i = 0; i < 16; i += 1) {
        tamParam.key[i] = keyBuffer[i];
    }
    NUR_TAM_PARAM *tam_param_pointer = &tamParam;
```
**NurApiGen2v2UntraceableByEPC**
```
NurApiGen2v2UntraceableByEPC(HANDLE hApi, DWORD passwd, BYTE *epcBuffer, DWORD epcBufferLen, struct NUR_UNTRACEABLE_PARAM *untraceable_param, DWORD szParam)
```
Using the following parameter set for example:
```
    NUR_UNTRACEABLE_PARAM untraceable_param{};
    untraceable_param.setU = TRUE;
    untraceable_param.hideEPC = TRUE;
    untraceable_param.epcWordLen = static_cast<DWORD>(std::stoi(ubEPC.substr(1, ubEPC.size()), nullptr, 2));
    untraceable_param.tidPolicy = NUR_TID_HIDE_ALL;
    untraceable_param.rangePolicy = NUR_UTRACE_RANGE_NORMAL;
    untraceable_param.hideUser = static_cast<BOOL>(bUserInput);
    untraceable_param.rxAttn = FALSE;

    NUR_UNTRACEABLE_PARAM *untraceable_param_pointer = &untraceable_param;
```
**Result**
With both of these calls returning an error code of: 
`5: Invalid command parameter(s); Invalid function parameter(s)`
I have tried multiple parameters in a variety of combinations, but the results remain the same.

I am working on Ubuntu 18.04.1 LTS. I can read, write, singulate, lock and set TAM2 keys successfully. 
Is this expected behaviour? Am I doing something wrong, or am I missing something? 

Thank you kindly, 
Vincent Mattana

**Comment by JuhaRautiainen** [comment]
Can you open the exact contents of all the parameters including the EPC parameters, please?

**Comment by VincentTruevolve** [comment]
Has been resolved through communication with @JuhaRautiainen.
Important issues to take note of include:
- Access password must be set and _locked_
- szParam is given by: sizeof(struct NUR_UNTRACEABLE_PARAM)
